version: '3.5'

services:
  # wp:
    # image: wordpress:latest # https://hub.docker.com/_/wordpress/
    # restart: always
    # # ports:
      # # - 127.0.0.1:80:80
    # volumes:
      # - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      # - ./wp-app:/var/www/html # Full wordpress project
      # #- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      # #- ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
    # environment:
      # WORDPRESS_DB_HOST: db
      # WORDPRESS_DB_NAME: "${DB_NAME}"
      # WORDPRESS_DB_USER: root
      # WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    # depends_on:
      # - db
    # networks:
     # wp_net_frontend:
     # wp_net_backend:
      # aliases:
       # - wp

  # wpcli:
    # image: wordpress:cli
    # restart: always
    # volumes:
      # - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      # - ./wp-app:/var/www/html
    # depends_on:
      # - db
      # - wp
    # networks:
    # # wp_net_frontend:
     # wp_net_backend:
      # aliases:
       # - wpcli
      
  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
#    ports:
#      - ${IP}:8080:80
    networks:
     wp_net_frontend:
     wp_net_backend:
      aliases:
       - pma

  db:
    image: mysql:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    restart: always
    ports:
      - 127.0.0.1:3306:3306
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--innodb-buffer-pool-size=64M',
        '--bind-address=0.0.0.0'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    networks:
     wp_net_frontend:
     wp_net_backend:
      aliases:
       - db

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/html:/etc/nginx/html:ro
      - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/etc/nginx/ssl:/etc/nginx/ssl:ro
      - ./certbot/certs:/etc/letsencrypt:ro
      - ./certbot/webroot:/opt/certbot:ro
    command: [nginx-debug, '-g', 'daemon off;']
    networks:
     wp_net_frontend:
     wp_net_backend:
      aliases:
       - nginx

  php:
    image: php:7.0-fpm
    restart: always
    volumes:
      - ./nginx/html:/var/www/html:ro
    networks:
    # wp_net_frontend:
     wp_net_backend:
      aliases:
       - php
       
  apache:
    #image: bitnami/apache:latest
    image: grommir/php:7.0-apache-mysql
    restart: always
    # ports:
      # - 80:80
      # - 443:443
    volumes:
      #- ./apache/html:/app:ro
      - ./apache/html:/var/www/html:ro
      #- ./apache/conf/vhosts:/vhosts:ro
      - ./apache/apache2:/etc/apache2:ro
      #- ./apache/conf/httpd.conf:/opt/bitnami/apache/conf/httpd.conf
    environment:
      APACHE_HTTP_PORT_NUMBER: 8080
    networks:
     wp_net_frontend:
     wp_net_backend:
      aliases:
       - apache

  certbot:
    image: nizovtsevnv/certbot
    restart: always
    volumes:
        - ./certbot/certs:/etc/letsencrypt:rw
        - ./certbot/webroot:/webroot:rw
    environment: 
        DOMAINS: "ap1.theme.by ap2.theme.by ap3.theme.by ap4.theme.by ap5.theme.by ng1.theme.by ng2.theme.by ng3.theme.by ng4.theme.by ng5.theme.by"
        EMAIL: "admin@theme.by"


networks:
  wp_net_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
  wp_net_backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24
